### ISSUE TITLE
Couple notes

### ISSUE THREAD

**Issue by DigiAngel** [broala/bro-protosigs#2]
Couple notes....the signature ID (protosig_whatever) can't contain "." characters or bro fails.  Also of note, it looks like the entire protosigs file is processed, so if you have this order:
~~~
signature protosig_dns_google {
  ip-proto == udp
  dst-port == 53
  payload /.*google/
  eval ProtoSig::match
}

signature protosig_dns {
  ip-proto == udp
  dst-port == 53
  payload /.*\x01\x00/
  eval ProtoSig::match
}
~~~
this will only show up as "dns" in conn.log since the last sig matched.  Conversely:
~~~
signature protosig_dns {
  ip-proto == udp
  dst-port == 53
  payload /.*\x01\x00/
  eval ProtoSig::match
}

signature protosig_dns_google {
  ip-proto == udp
  dst-port == 53
  payload /.*google/
  eval ProtoSig::match
}
~~~
this will match as expected and show up in conn.log as "dns_google".  So you add your generic match first, then the specific ones after.  Might wanna document this somewhere :)

**Comment by sethhall** [comment]
This was designed for protocol matching, but you seem to be using it here for more generic connection tagging.  I think that you are actually meaning to file a ticket about the behavior and documentation of Bro's signature support.  Could you file a ticket at the Bro ticket tracker with thoughts on behavior and desired improvements to Bro's signature support?  
    http://tracker.bro.org

Thanks!
  .Seth

**Comment by DigiAngel** [comment]
Awesome...thanks Seth...is usual I chose the wrong medium..yugh..sorry for the noise.
